version: '3'
services:
  app:
    build: .
    ports:
      - '3030:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./start.sh"]
    networks:
      - app-net
  db:
    image: mysql:8.0.21
    platform: linux/amd64
    container_name: ${CONTAINER_NAME}
    ports:
      - '3306:3306'
    volumes:
      - go_mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
    networks:
      - app-net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-net
volumes:
  go_mysql_data:
networks:
  app-net: